# Generated by Django 3.1.7 on 2021-03-19 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='price of product in EUR - must be gt 0', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.IntegerField(default=0, help_text='number of items available from this product to be sold - must be gte 0', validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(help_text='product name', max_length=255)),
                ('seller', models.ForeignKey(help_text='creator of product from user model - must be admin', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
